/** @format */

import './globals.css';

import type { Metadata } from 'next';
import SessionProvider from '@/app/components/SessionProvider';
import { authOptions } from './api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	if (!session) redirect('/api/auth/signin');

	return (
		<html lang='en'>
			<body className={``}>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
